package.json
src/index.js

@VictorBjelkholm after some long hours of debugging, we managed to find the issue.
multiplex from the listener side was opening the streams before the dialer had the time to mount the muxer and so, when it got to mount the muxer, some data events were already emitted because of the resume call.
This was super tough one to fix! Big thanks for @pgte for pairing with me debugging it.
//cc @dignifiedquire you will find this hilarious
//cc @haadcode @RichardLitt stream muxer is under way!

fix: dropped packed

---

src/muxer.js
test/muxer.spec.js

This prevents uncaught "Multiplexer is destroyed" exceptions from being thrown into the void.

fix: catch Multiplexer is destroyed error into callback

---

package.json
src/internals/index.js

* This also updates dependencies to the latest
The js-libp2p tests exposed an issue with the latest of libp2p-mplex, where because `Multiplex._send()` is potentially doing 2 pushed, we can get into a bad state where `readable.push()` returns false, but we still have data to give. This could result in streams not closing properly, which was happening in the libp2p tests that exposed the issue.
This PR concatenates the varint and data pushes (if there is data) into a single push. This avoids the scenario of there being residual data to send when `.push` returns false.
You can see the passing build of libp2p using this branch here: https://ci.ipfs.team/blue/organizations/jenkins/libp2p%2Fjs-libp2p/detail/test%2Fgoodbye-mplex/2/pipeline

fix: improve resiliency of internals _send

---

src/muxer.js
test/muxer.spec.js

`muxer.end` was previously waiting for the 'close' event before calling its callback. If the stream was already destroyed, close would not be triggered and the callback would never be called.
Since close is emitted synchronously in the `multiplex.destroy` method there is no need to bind a listener and we can execute the callback immediately following the destroy.
This will also avoid leaking event listeners on end, and the accompanying warning when numerous muxers are closed simultaneously.

fix: muxer.end will no longer hang

---

examples/dialer.js
examples/listener.js
package.json
src/internals/channel.js
src/internals/index.js
src/muxer.js
test/internals.node.js
test/muxer.spec.js

* Update dependencies
* Don't override stream.destroy as it's against the Stream api
* Override emit to only throw errors if we have listeners. This replicates some logic that was removed when fixing the stream.destroy override.
* Fix lint warnings

Improve error handling

---

src/mplex.js
src/restrict-size.js
src/stream.js
test/stream.spec.js

As per the discussion in https://github.com/libp2p/js-libp2p-kad-dht/issues/154, this adds automatic message splitting to mplex for when messages are bigger than the max message size.

feat: message splitting

---

src/coder/decode.js
src/coder/encode.js

This imports the `BufferList` class that does not extend duplex stream. This gets us one step closer to removing readable-stream from the bundle.

perf: small bl

---

.aegir.js
package.json
src/coder/decode.js
src/coder/encode.browser.js
src/coder/encode.js
src/mplex.js
test/coder.spec.js
test/restrict-size.spec.js
test/stream.spec.js

Buffer lists are still used internally but any Buffers created by this module are now Uint8Arrays.
BREAKING CHANGE:
- All use of node Buffers has been replaced with Uint8Arrays

fix: replace node buffers with uint8arrays

---

package.json
src/coder/decode.js
src/coder/encode.browser.js
src/coder/encode.js
src/mplex.js
src/restrict-size.js
src/stream.js
test/stream.spec.js

This adds some more aggressive closures to streams on abort and reset. It was previously possible for unwritten streams to not properly end when aborted/reset, which would result in them not properly notifying libp2p/application code of the termination. This could also result in streams lingering.
* This also includes some formatting updates needed due to the Aegir bump
I'd like to do some more clean up here but am reserving that for https://github.com/libp2p/js-libp2p-mplex/pull/115, which will create some breaking behavior.
This should also resolve part of https://github.com/libp2p/js-libp2p-mplex/pull/113.

fix: stream close

---

.aegir.js
.travis.yml
package.json
test/restrict-size.spec.js
test/stream.spec.js

Pull in latest bl, errcode, etc

chore: update deps

---

src/coder/decode.js

**Motivation**
+ As noted in https://github.com/ChainSafe/lodestar/issues/3467, 80%-90% of the `varint.decode()` function time is used to handle `varint.decode()` RangeError because the buffer length is 0
+ after consuming the whole length, _buffer has 0 length so don't want to bother varint

perf: do not call varint.decode() if buffer has 0 length

---

examples/dialer.js
package.json
src/stream.js

`AbortController` and `AbortSignal` are in browsers and LTS node so the `abort-controller` and `native-abort-controller` deps aren't required any more.

fix: remove abort controller dep

---

package.json
src/mplex.ts
src/stream.ts
test/stream.spec.ts

This also now throws an error when a write is attempted on a non existent stream. Previously we would just send the message, but this is against the mplex protocol.
Refs: #120
Supersedes: #115

feat: close read and write streams

---

README.md
package.json
src/index.ts
src/mplex.ts
src/stream.ts
test/mplex.spec.ts

* Updates interfaces
* Returns `StreamMuxer` type
* Adds `maxIncomingStreamsPerConnection` and `maxOutgoingStreamsPerConnection` options to stop lots of incoming streams preventing outgoing streams from being opened
BREAKING CHANGE: updates to simplified connection interface

fix!: limit incoming and outgoing streams separately

---

package.json
src/mplex.ts

Adds the close() function to the StreamMuxer interface.
Fixes #185

fix!: upgrade to interface-stream-muxer 2.0.0

---

src/mplex.ts
test/mplex.spec.ts

Instead of creating a stream or throwing an error, discard any NEW_STREAM messages that put us over the inbound stream limit and send a message to the initiator resetting that stream.

fix: reset stream when over inbound stream limit

---

src/stream.ts
test/stream.spec.ts

To allow detecting the same error condition with different stream
muxer implementations, remove the `MPLEX_` prefix from the error
codes thrown by this module.
Also adds a `ERR_DOUBLE_SINK` code when when `.sink` is called
multiple times instead of only throwing `ERR_SINK_ENDED` when `.sink`
is called after a stream is closed for reading.
Refs: https://github.com/ChainSafe/js-libp2p-yamux/issues/4

fix: remove MPLEX_ prefix from error codes

---

package.json
src/decode.ts
src/encode.ts
src/mplex.ts

Updates dep and replaces `.slice` for `.subarray` to avoid copying memory unnecessarily.

deps: update uint8arraylist dep

---

package.json
src/decode.ts
src/message-types.ts
src/mplex.ts
src/stream.ts
test/coder.spec.ts
test/mplex.spec.ts
test/restrict-size.spec.ts
test/stream.spec.ts

To make sure there's no chance we end up copying memory to a new
location only to pass it to a stream handler, return `Uint8ArrayList`s
for the `data` property of multiplexed messages.
The stream interface looks like this:
```
Stream extends Duplex<Uint8ArrayList, Uint8ArrayList | Uint8Array>
```
That is, it's a Duplex whose source emits `Uint8ArrayList`s but the
sink can accept `Uint8ArrayList`s or `Uint8Arrays`.
Depends on:
BREAKING CHANGE: mulitplexed streams now emit `Uint8ArrayList`s and not `Uint8Array`s to handle the case for when transports have smaller chunk sizes than the multiplexer

fix!: emit uint8arraylists for data

---

benchmark/send-and-receive.js
package.json

**Motivation**
- Track the performance of libp2p-mplex
**Description**
- Use `@dapplion/benchmark` module which is used in libp2p-gossipsub
**Sample output**
`npm run benchmark`
```
benchmark mplex
✔ send and receive 1000 items                                          4237288 ops/s    236.0000 ns/op        -    4983194 runs    120 s
```

feat: add benchmark

---

README.md
package.json
src/encode.ts
src/index.ts
src/mplex.ts
test/compliance.spec.ts
test/mplex.spec.ts

If we hit the inbound stream limit and the remote peer continues to attempt to open new streams at a rate we consider to be unreasonable, close the connection.
Mplex has no notion of backpressure so this is all we can really do to protect ourselves.

feat: close connections when too many streams are opened

---

src/stream.ts
test/stream.spec.ts

Fixes a regression in the ts port - messages larger than `maxMsgSize` should be chunked and sent as a series of smaller messages.

fix: chunk messages over maxMsgSize

---

src/stream.ts

Related to https://github.com/libp2p/js-libp2p/issues/1342
Shaves ~100ms when sending small chunks but we are still not close to 0.36 speed

fix: optimize stream sink for small messages

---

benchmark/send-and-receive.js
package.json

Use [benchmark](https://www.npmjs.com/package/benchmark) for running benchmarks so we can run them in the browser too.

chore: refactor benchmarks for use in the browser

---

package.json
src/mplex.ts

The stats are useless since every connection has a stream muxer but they all record stats to the same keys meaning they overwrite each other.

fix: remove tracked map as the stats overwrite each other

---

benchmark/send-and-receive.js

Refactors benchmark to use exported factory function instead of instantiating an instance of the class which is no longer exported.

chore: update benchmark

---

src/encode.ts
src/mplex.ts
src/stream.ts

Messages are serialized to multiple buffers, instead of yielding each buffer one by one, create single buffers that contain the whole serialized message. This greatly improves transport performance as writing one big buffer is a lot faster than writing lots of small buffers to network sockets etc.
This is similar to what the old CJS version did, except it yielded `BufferList`s which were then `.slice()`ed elsewhere to turn them into a single `Buffer`.
```
testing 0.40.x-mplex
sender 3276811 messages 32 invocations
sender 6553636 bufs 17 b
105 MB in 32 B chunks in 26373ms
```
```
testing 0.40.x-mplex
sender 3276811 messages 3276808 invocations
sender 3276811 bufs 34 b
105 MB in 32 B chunks in 16172ms
```
```
testing 0.40.x-mplex
sender 3276811 messages 1638408 invocations
1638411 bufs 68 b …
```

fix: yield single buffers

---

README.md
package.json
src/decode.ts
src/index.ts
src/mplex.ts
test/restrict-size.spec.ts

It's possible to receive lots of small messages in one buffer that can be larger than the max message size, so limit the unprocessed message queue size separately from the max message size.

fix: limit unprocessed message queue size separately to message size

---

src/encode.ts
test/coder.spec.ts
test/mplex.spec.ts
test/restrict-size.spec.ts

At runtime the encoder is supplied lists of messages by a `pushableV`, the only time the source has individual messages is during test runs so simplify by only accepting lists of messages.

fix: only accept lists of messages in encoder

---

README.md

Mplex class is now not exported anymore and so the user is asked to initiate the object using a utility function called "mplex"

docs: update interface definition in readme.md

---

package.json
src/mplex.ts
src/stream.ts

Replaces [err-code](https://github.com/IndigoUnited/js-err-code/blob/master/index.js) with [CodeError](https://github.com/libp2p/js-libp2p-interfaces/pull/314)
Related: [js-libp2p#1269](https://github.com/libp2p/js-libp2p/issues/1269)
Changes
- removes err-code from dependencies
- adds @libp2p/interfaces@3.2.0 to dependencies
- uses CodeError in place of err-code

chore: replace err-code with CodeError

---

package.json
src/alloc-unsafe-browser.ts
src/alloc-unsafe.ts
src/decode.ts
src/encode.ts
src/mplex.ts
src/stream.ts
test/fixtures/utils.ts
test/restrict-size.spec.ts
test/stream.spec.ts

Also reverting typescript to `4.9.5` because a3590af093dee73c873aef1539bc8d81b0d61b08 upgraded it, but [aegir depends on eslint-plugin-etc](https://github.com/ipfs/aegir/blob/17f7230c65f6227d2d6d9a73921e7e9034364ebd/package.json#L260) ( [as well as eslint-config-ipfs](https://github.com/ipfs/eslint-config-ipfs/blob/main/package.json#L24) which also depends on `eslint-plugin-etc`) which is incompatible with TS5 atm https://github.com/cartant/eslint-plugin-etc/issues/53.

deps(dev): Upgrade aegir to 38.1.7

---

.gitignore
package.json
src/decode.ts
src/mplex.ts

libp2p streams are now explicit about the types of sync/sources they provide, showing that they are `AsyncGenerator`s and not just `AsyncIterable`s.
BREAKING CHANGE: the type of the source/sink properties have changed

deps!: update to new stream type deps
